// <auto-generated />
using System;
using AssessmentService.Infrastructure.Persistance.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssessmentService.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(AssessmentDbContext))]
    partial class AssessmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("latin1_swedish_ci")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AssessmentService.Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("assessment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int(11)")
                        .HasColumnName("duration_minutes");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int(11)")
                        .HasColumnName("total_questions");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("AssessmentId")
                        .HasName("PRIMARY");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AssessmentAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("answer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<int>("AssessmentQuestionId")
                        .HasColumnType("int(11)")
                        .HasColumnName("assessment_question_id");

                    b.Property<int>("AttemptsId")
                        .HasColumnType("int(11)")
                        .HasColumnName("attempts_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_correct");

                    b.Property<string>("SelectedOptionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("selected_option_id")
                        .HasComment("Reference to QuestionOption in Question Service");

                    b.HasKey("AnswerId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssessmentQuestionId" }, "assessment_question_id");

                    b.HasIndex(new[] { "AttemptsId" }, "attempts_id");

                    b.HasIndex(new[] { "SelectedOptionId" }, "idx_selected_option");

                    b.ToTable("assessment_answer", (string)null);
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Property<int>("AssessmentQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("assessment_question_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssessmentQuestionId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int(11)")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("question_id")
                        .HasComment("Reference to Question Service");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("AssessmentQuestionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssessmentId" }, "assessment_id");

                    b.HasIndex(new[] { "AssessmentId", "QuestionId" }, "idx_assessment_question")
                        .IsUnique();

                    b.ToTable("assessment_question", (string)null);
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AssignmentAttempt", b =>
                {
                    b.Property<int>("AttemptsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("attempts_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttemptsId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int(11)")
                        .HasColumnName("assessment_id");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("attempt_number")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("AttemptsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssessmentId" }, "assessment_id")
                        .HasDatabaseName("assessment_id1");

                    b.ToTable("assignment_attempts", (string)null);
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.GradingFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("feedback_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("AttemptsId")
                        .HasColumnType("int(11)")
                        .HasColumnName("attempts_id");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int(11)")
                        .HasColumnName("correct_count")
                        .HasComment("Số câu trả lời đúng");

                    b.Property<decimal>("CorrectPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("correct_percentage")
                        .HasComment("Phần trăm câu đúng (%)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_score")
                        .HasComment("Tổng điểm trên thang 10");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.Property<int>("WrongCount")
                        .HasColumnType("int(11)")
                        .HasColumnName("wrong_count")
                        .HasComment("Số câu trả lời sai");

                    b.Property<decimal>("WrongPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("wrong_percentage")
                        .HasComment("Phần trăm câu sai (%)");

                    b.HasKey("FeedbackId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AttemptsId" }, "attempts_id")
                        .IsUnique()
                        .HasDatabaseName("attempts_id1");

                    b.ToTable("grading_feedback", (string)null);
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AssessmentAnswer", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.AssessmentQuestion", "AssessmentQuestion")
                        .WithMany("AssessmentAnswers")
                        .HasForeignKey("AssessmentQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("assessment_answer_ibfk_1");

                    b.HasOne("AssessmentService.Domain.Entities.AssignmentAttempt", "Attempts")
                        .WithMany("AssessmentAnswers")
                        .HasForeignKey("AttemptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("assessment_answer_ibfk_2");

                    b.Navigation("AssessmentQuestion");

                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("assessment_question_ibfk_1");

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AssignmentAttempt", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssignmentAttempts")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("assignment_attempts_ibfk_1");

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.GradingFeedback", b =>
                {
                    b.HasOne("AssessmentService.Domain.Entities.AssignmentAttempt", "Attempts")
                        .WithOne("GradingFeedback")
                        .HasForeignKey("AssessmentService.Domain.Entities.GradingFeedback", "AttemptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("grading_feedback_ibfk_1");

                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentQuestions");

                    b.Navigation("AssignmentAttempts");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Navigation("AssessmentAnswers");
                });

            modelBuilder.Entity("AssessmentService.Domain.Entities.AssignmentAttempt", b =>
                {
                    b.Navigation("AssessmentAnswers");

                    b.Navigation("GradingFeedback");
                });
#pragma warning restore 612, 618
        }
    }
}
