version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: edulit-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - edulit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:5.7.43
    container_name: edulit-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: edulit_assessment_db
      MYSQL_USER: developer
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - edulit-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: AuthService.Api/Dockerfile
    container_name: edulit-auth-service
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=auth_db;Username=postgres;Password=postgres"
      Jwt__Key: "THIS_IS_A_MUCH_LONGER_AND_MORE_SECURE_SUPER_SECRET_KEY_123456789"
      Jwt__Issuer: "EduLit.Auth"
      Jwt__Audience: "EduLit.Users"
      Jwt__ExpiresInHours: "48"
    ports:
      - "8001:8080"
    networks:
      - edulit-network
    entrypoint: >
      /bin/sh -c "
      until pg_isready -h postgres -p 5432 -U postgres;
      do echo 'Waiting for PostgreSQL...'; sleep 2; done;
      echo 'PostgreSQL is ready!';
      dotnet AuthService.Api.dll
      "

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: edulit-api-gateway
    restart: on-failure
    depends_on:
      - auth-service
    ports:
      - "8000:8080"
    networks:
      - edulit-network

volumes:
  pgdata:
  mysqldata:

networks:
  edulit-network:
    driver: bridge
